version: "3.7"

services:
  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 8001:8000
      - PORT_PORTAINER_WEB:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/portainer/data:/data
      - ./shared:/shared
    environment:
      - TZ=${TZ}
  
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: always
    volumes:
      - ${CONFIGDIR}/organizr:/config
      - ./shared:/shared
    ports:
      - ${PORT_ORGANIZR}:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 23 * * SUN" --cleanup

  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
      - ${PORT_UPKUMA}:3001
    volumes:
      - ${CONFIGDIR}/uptime-kuma:/app/data

  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINLIST}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=${DEBUG_LOG}
    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional
    restart: unless-stopped

  gloomhaven-helper-headless:
    container_name: gloomhaven-helper-headless
    image: grepnull/gloomhaven-helper-headless:latest
    volumes:
      - ${CONFIGDIR}/gloomhaven-helper-headless/ghh:/root/.ghh
