name: "media-request"

services:

####################
# Jellyseerr
####################

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest

    networks:
      - htpc-net
      - caddy-net # provides access for the reverse proxy

    ports:
      - ${PORT_HTPC_REQUESTS}:5055

    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TZ}

    labels:
      - diun.enable=true
      - homepage.group=Media
      - homepage.name=Request Movies and TV Shows
      - homepage.icon=jellyseerr
      - homepage.href=http://${SERVER_URL}:${PORT_HTPC_REQUESTS}
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://${SERVER_URL}:${PORT_HTPC_REQUESTS}
      - homepage.widget.key=${HOMEPAGE_JELLYSEERR_API}

    volumes:
        - ${CONFIGDIR}/jellyseerr:/app/config
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    restart: always


networks:
  caddy-net:
    name: caddy-net
    external: true
  htpc-net:
    name: htpc-net
    external: true
